version: '1.0'
name: ci-xmake-build-L1
displayName: ci-xmake-build-L1
triggers:
  trigger: auto
  pr:
    branches:
      precise:
        - branch-1.2
    paths:
      precise:
        - src/Kernel/Abstractions/
        - src/Kernel/Containers/
        - src/Kernel/Types/

variables:
  XMAKE_MAIN_REPO: 'https://gitee.com/XmacsLabs/xmake-repo.git'

stages:
  - name: xmake
    displayName: xmake
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build
        displayName: Build and test for L1 kernel
        gccVersion: '9.4'
        commands:
          - apt-get update
          - apt-get install -y software-properties-common libpng-dev zlib1g-dev libjpeg-turbo8-dev libfreetype-dev libsqlite3-dev qtbase5-dev libqt5svg5-dev libfontconfig-dev
          - /usr/bin/add-apt-repository ppa:xmake-io/xmake
          - apt-get update
          - apt-get install xmake
          - xmake repo -u --root
          - xmake config --yes --root
          - xmake build --root libkernel_l1
        caches: [
          build/.build_cache,
        ]
        notify: []
        strategy:
          retry: '0'
          stepTimeout: 30
